version: "3"

services:
  mongodb_container:
    image: mongo:latest
    restart: always
    container_name: mongodb_container
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_DATABASE: ${MONGO_INITDB_ROOT_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
